# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
#permalink:        pretty
  #relative_permalinks: true

# Setup
title:           'Beatrice Giudici'
tagline:          'Hi, welcome to my personal page!'
description:      'This is the personal page of Beatrice Giudici'
url:              https://beagiudici.github.io
baseurl:         

author:
  name:           'Beatrice Giudici'

    #plugins: [jekyll-paginate]
    #paginate:         5

# Custom vars
version:          1.0.0

github:           
  repo:           https://github.com/BeaGiudici/
