# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:           'Beatrice Giudici'
tagline:          'My personal page'
description:      'Hi, welcome to my personal page!'
url:              https://beagiudici.github.io
baseurl:         

author:
  name:           'Beatrice Giudici'

plugins: [jekyll-paginate]
paginate:         5

# Custom vars
version:          1.0.0

github:           
  repo:           https://github.com/BeaGiudici/
